In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("data_cleaning.csv")
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [6]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [7]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [8]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [9]:
df.dropna(axis=0)

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [11]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [14]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [16]:
df.fillna(method="ffill")

C:\Users\HP\AppData\Local\Temp\ipykernel_24860\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [17]:
df.fillna(method="bfill")

C:\Users\HP\AppData\Local\Temp\ipykernel_24860\3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [18]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [19]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [20]:
# String Operations
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [21]:
df["City"].str.contains("dELHI",case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [24]:
df["Email"].str.split(".com")

0    [alice@example, ]
1    [charlie@example]
2      [bob@example, ]
3    [charlie@example]
4    [david@example, ]
5       [eve@domain, ]
6    [alice@example, ]
7    [alice@example, ]
8    [charlie@example]
Name: Email, dtype: object

In [31]:
df2=df.dropna().copy()
df2

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [32]:
df2["Age"]=df2["Age"].astype(int)

In [33]:
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

In [38]:
df2["Join Date"]=pd.to_datetime(df2["Join Date"],dayfirst=True)
df2

    Name  Age         City Gender              Email  Join Date
0  Alice   25     New York      F  alice@example.com 2021-05-01
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15
4  David   22       Mumbai      M  david@example.com 2019-11-12
6  Alice   25     New York      F  alice@example.com 2021-05-01
7  Alice   25     New York      F  alice@example.com 2021-05-01

In [39]:
# Functions 
df2

    Name  Age         City Gender              Email  Join Date
0  Alice   25     New York      F  alice@example.com 2021-05-01
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15
4  David   22       Mumbai      M  david@example.com 2019-11-12
6  Alice   25     New York      F  alice@example.com 2021-05-01
7  Alice   25     New York      F  alice@example.com 2021-05-01

In [40]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [44]:
df2["Age Group"]=df2["Age"].apply(lambda x:"Adult" if x>=25 else "Minor")
df2

    Name  Age         City Gender              Email  Join Date Age Group
0  Alice   25     New York      F  alice@example.com 2021-05-01     Adult
2    Bob   30  Los Angeles      M    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai      M  david@example.com 2019-11-12     Minor
6  Alice   25     New York      F  alice@example.com 2021-05-01     Adult
7  Alice   25     New York      F  alice@example.com 2021-05-01     Adult

In [46]:
gender_map={"M":"Male","F":"Female"}
df2["Gender"]=df2["Gender"].map(gender_map)
df2

    Name  Age         City  Gender              Email  Join Date Age Group
0  Alice   25     New York  Female  alice@example.com 2021-05-01     Adult
2    Bob   30  Los Angeles    Male    bob@example.com 2020-06-15     Adult
4  David   22       Mumbai    Male  david@example.com 2019-11-12     Minor
6  Alice   25     New York  Female  alice@example.com 2021-05-01     Adult
7  Alice   25     New York  Female  alice@example.com 2021-05-01     Adult

In [47]:
df2["City"]=df2["City"].replace({"Delhi":"New Delhi","Mumbai":"Bombay"})
df2

    Name  Age         City  Gender              Email  Join Date Age Group
0  Alice   25     New York  Female  alice@example.com 2021-05-01     Adult
2    Bob   30  Los Angeles    Male    bob@example.com 2020-06-15     Adult
4  David   22       Bombay    Male  david@example.com 2019-11-12     Minor
6  Alice   25     New York  Female  alice@example.com 2021-05-01     Adult
7  Alice   25     New York  Female  alice@example.com 2021-05-01     Adult