In [1]:
import numpy as np

In [2]:
import pandas as pd

In [9]:
df=pd.read_excel("data.xlsx")
df

,Actor,Film,Genre,Year,Box Office (Cr INR),IMDb Rating
0,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
1,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4
2,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0
3,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1
4,Ranveer Singh,Simmba,Action,2018,400,5.4
5,Hrithik Roshan,War,Action Thriller,2019,475,6.5
6,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
8,Vicky Kaushal,Uri,War,2019,342,8.2
9,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0

In [11]:
df["Actor"][1]

'Aamir Khan'

In [13]:
df[["Actor","Film"]]

                Actor             Film
0      Shah Rukh Khan          Pathaan
1          Aamir Khan           Dangal
2         Salman Khan  Tiger Zinda Hai
3       Ranbir Kapoor           Animal
4       Ranveer Singh           Simmba
5      Hrithik Roshan              War
6        Akshay Kumar       Good Newwz
7          Ajay Devgn          Tanhaji
8       Vicky Kaushal              Uri
9  Ayushmann Khurrana       Dream Girl

In [15]:
df.iloc[0]

Actor                  Shah Rukh Khan
Film                          Pathaan
Genre                          Action
Year                             2023
Box Office (Cr INR)              1050
IMDb Rating                       5.9
Name: 0, dtype: object

In [17]:
df.loc[8,"Film"]

'Uri'

In [18]:
df.loc[0:2,["Actor","Film"]]

            Actor             Film
0  Shah Rukh Khan          Pathaan
1      Aamir Khan           Dangal
2     Salman Khan  Tiger Zinda Hai

In [19]:
df.at[1,"Actor"]

'Aamir Khan'

In [20]:
df.iat[1,3]

np.int64(2016)

In [21]:
cond=df["IMDb Rating"]>7

In [23]:
df[cond]["Actor"]

1       Aamir Khan
3    Ranbir Kapoor
7       Ajay Devgn
8    Vicky Kaushal
Name: Actor, dtype: object

In [24]:
cond2=df["Year"]>2020

In [26]:
df[cond&cond2]

           Actor    Film         Genre  Year  Box Office (Cr INR)  IMDb Rating
3  Ranbir Kapoor  Animal  Action Drama  2023                  915          7.1

In [28]:
df[cond | cond2]

,Actor,Film,Genre,Year,Box Office (Cr INR),IMDb Rating
0,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
1,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4
3,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
8,Vicky Kaushal,Uri,War,2019,342,8.2

In [29]:
df.query("Year>2019")

,Actor,Film,Genre,Year,Box Office (Cr INR),IMDb Rating
0,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
3,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5