In [1]:
# Learning melt and pivot

In [2]:
import pandas as pd

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}
 
df = pd.DataFrame(data)

In [4]:
df

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [9]:
df.melt(id_vars={"Name"}, value_vars= {"Math","Science","English"}, var_name="Subject",value_name="Score")

      Name  Subject  Score
0    Alice  English     88
1      Bob  English     85
2  Charlie  English     94
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice     Math     85
7      Bob     Math     78
8  Charlie     Math     92

In [10]:
df.pivot(index="Name", columns="Subject", values="Score")

KeyError: 'Subject'