In [1]:
import pandas as pd

In [2]:
# You can now run the same analysis I gave earlier:

# Count Movies vs TV Shows

# Top genres

# Top actors

# Trend over years

In [3]:
df=pd.read_csv("mock_netflix_data.csv")

In [4]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Title 1,Director A,"Actor A, Actor D",NaN,"November 12, 2019",2012,TV-14,1 Seasons,"Dramas, International Movies",Lorem ipsum dolor sit amet.
1,s2,Movie,Title 2,NaN,"Actor A, Actor B",NaN,"April 06, 2019",2000,TV-MA,3 Seasons,"Children & Family Movies, Comedies",Lorem ipsum dolor sit amet.
2,s3,Movie,Title 3,Director B,"Actor A, Actor D",India,"December 22, 2017",2014,NaN,108 min,Documentaries,Lorem ipsum dolor sit amet.
3,s4,Movie,Title 4,Director B,"Actor E, Actor F",Canada,"July 12, 2018",2021,TV-14,4 Seasons,Documentaries,Lorem ipsum dolor sit amet.
4,s5,Movie,Title 5,NaN,"Actor E, Actor F",United States,"November 17, 2015",2002,TV-14,4 Seasons,"Dramas, International Movies",Lorem ipsum dolor sit amet.
...,...,...,...,...,...,...,...,...,...,...,...,...
95,s96,TV Show,Title 96,NaN,"Actor E, Actor F",United States,"April 27, 2015",2016,PG-13,2 Seasons,"Dramas, International Movies",Lorem ipsum dolor sit amet.
96,s97,Movie,Title 97,Director C,"Actor E, Actor F",United Kingdom,"September 03, 2018",2020,TV-MA,4 Seasons,Documentaries,Lorem ipsum dolor sit amet.
97,s98,TV Show,Title 98,Director C,NaN,NaN,"May 30, 2019",2021,TV-14,1 Seasons,Action & Adventure,Lorem ipsum dolor sit amet.
98,s99,TV Show,Title 99,Director B,"Actor C, Actor D",United Kingdom,"February 16, 2016",2006,TV-MA,14 min,"Children & Family Movies, Comedies",Lorem ipsum dolor sit amet.
99,s100,TV Show,Title 100,Director B,NaN,United Kingdom,"July 05, 2019",2005,R,4 Seasons,"Comedies, Dramas",Lorem ipsum dolor sit amet.

In [8]:
df.groupby("type").size()

type
Movie      52
TV Show    48
dtype: int64

In [9]:
df['type'].value_counts()

type
Movie      52
TV Show    48
Name: count, dtype: int64

In [10]:
df.dropna()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3,s4,Movie,Title 4,Director B,"Actor E, Actor F",Canada,"July 12, 2018",2021,TV-14,4 Seasons,Documentaries,Lorem ipsum dolor sit amet.
12,s13,Movie,Title 13,Director C,"Actor E, Actor F",Canada,"November 05, 2020",2006,TV-MA,3 Seasons,"Comedies, Dramas",Lorem ipsum dolor sit amet.
13,s14,Movie,Title 14,Director C,"Actor A, Actor B",Canada,"February 08, 2015",2020,PG-13,4 Seasons,"Comedies, Dramas",Lorem ipsum dolor sit amet.
14,s15,TV Show,Title 15,Director B,"Actor C, Actor D",United States,"December 22, 2020",2015,TV-14,4 Seasons,Action & Adventure,Lorem ipsum dolor sit amet.
22,s23,Movie,Title 23,Director A,"Actor A, Actor B",Canada,"April 09, 2016",2013,TV-14,3 Seasons,Action & Adventure,Lorem ipsum dolor sit amet.
24,s25,TV Show,Title 25,Director C,"Actor A, Actor B",United Kingdom,"April 06, 2017",2010,TV-MA,3 Seasons,Documentaries,Lorem ipsum dolor sit amet.
26,s27,Movie,Title 27,Director C,"Actor A, Actor B",India,"December 02, 2021",2017,R,78 min,Action & Adventure,Lorem ipsum dolor sit amet.
27,s28,TV Show,Title 28,Director A,"Actor E, Actor F",India,"September 10, 2021",2004,PG-13,3 Seasons,"Children & Family Movies, Comedies",Lorem ipsum dolor sit amet.
31,s32,TV Show,Title 32,Director B,"Actor E, Actor F",Canada,"April 06, 2019",2006,R,2 Seasons,"Dramas, International Movies",Lorem ipsum dolor sit amet.
33,s34,TV Show,Title 34,Director A,"Actor E, Actor F",United States,"July 01, 2020",2003,TV-MA,48 min,"Comedies, Dramas",Lorem ipsum dolor sit amet.
37,s38,Movie,Title 38,Director B,"Actor A, Actor D",India,"November 11, 2020",2006,TV-MA,3 Seasons,Documentaries,Lorem ipsum dolor sit amet.
41,s42,TV Show,Title 42,Director B,"Actor C, Actor D",United States,"November 09, 2018",2015,TV-14,66 min,"Children & Family Movies, Comedies",Lorem ipsum dolor sit amet.
48,s49,Movie,Title 49,Director C,"Actor A, Actor B",India,"March 09, 2017",2021,PG-13,1 min,Action & Adventure,Lorem ipsum dolor sit amet.
50,s51,Movie,Title 51,Director A,"Actor E, Actor F",United Kingdom,"August 17, 2016",2014,TV-14,2 Seasons,"Comedies, Dramas",Lorem ipsum dolor sit amet.
51,s52,Movie,Title 52,Director C,"Actor A, Actor B",United States,"April 30, 2021",2018,TV-MA,5 Seasons,Action & Adventure,Lorem ipsum dolor sit amet.
55,s56,TV Show,Title 56,Director A,"Actor A, Actor B",India,"March 30, 2015",2002,R,5 Seasons,"Children & Family Movies, Comedies",Lorem ipsum dolor sit amet.
56,s57,TV Show,Title 57,Director B,"Actor A, Actor B",United Kingdom,"August 22, 2016",2000,TV-MA,4 Seasons,"Comedies, Dramas",Lorem ipsum dolor sit amet.
57,s58,TV Show,Title 58,Director A,"Actor A, Actor B",Canada,"May 26, 2020",2020,TV-14,4 Seasons,"Dramas, International Movies",Lorem ipsum dolor sit amet.
58,s59,TV Show,Title 59,Director C,"Actor A, Actor D",United States,"December 17, 2020",2006,R,1 Seasons,"Dramas, International Movies",Lorem ipsum dolor sit amet.
63,s64,Movie,Title 64,Director C,"Actor C, Actor D",India,"January 27, 2021",2010,TV-14,5 Seasons,"Comedies, Dramas",Lorem ipsum dolor sit amet.
64,s65,TV Show,Title 65,Director A,"Actor E, Actor F",United Kingdom,"June 18, 2015",2000,PG-13,63 min,"Children & Family Movies, Comedies",Lorem ipsum dolor sit amet.
66,s67,TV Show,Title 67,Director B,"Actor E, Actor F",India,"June 17, 2018",2013,TV-MA,94 min,"Children & Family Movies, Comedies",Lorem ipsum dolor sit amet.
78,s79,Movie,Title 79,Director B,"Actor E, Actor F",United Kingdom,"March 03, 2018",2007,TV-MA,66 min,"Comedies, Dramas",Lorem ipsum dolor sit amet.
80,s81,TV Show,Title 81,Director A,"Actor C, Actor D",Canada,"February 16, 2021",2005,R,115 min,Action & Adventure,Lorem ipsum dolor sit amet.
91,s92,Movie,Title 92,Director A,"Actor A, Actor B",United Kingdom,"October 22, 2015",2000,TV-14,136 min,Documentaries,Lorem ipsum dolor sit amet.
93,s94,Movie,Title 94,Director A,"Actor A, Actor B",United States,"June 26, 2020",2019,PG-13,51 min,Documentaries,Lorem ipsum dolor sit amet.
96,s97,Movie,Title 97,Director C,"Actor E, Actor F",United Kingdom,"September 03, 2018",2020,TV-MA,4 Seasons,Documentaries,Lorem ipsum dolor sit amet.
98,s99,TV Show,Title 99,Director B,"Actor C, Actor D",United Kingdom,"February 16, 2016",2006,TV-MA,14 min,"Children & Family Movies, Comedies",Lorem ipsum dolor sit amet.

In [14]:
df.groupby("listed_in").size().sort_values(ascending=False)

listed_in
Children & Family Movies, Comedies    26
Comedies, Dramas                      20
Documentaries                         14
Action & Adventure                    13
Dramas, International Movies          11
dtype: int64

In [17]:
df['cast'].value_counts().sort_values(ascending=False)

cast
Actor A, Actor B    24
Actor E, Actor F    24
Actor C, Actor D    22
Actor A, Actor D    13
Name: count, dtype: int64

In [18]:
from collections import Counter

print(Counter(', '.join(df['cast'].fillna('')).split(', ')).most_common(10))

[('Actor A', 37), ('Actor D', 35), ('Actor B', 24), ('Actor E', 24), ('Actor F', 24), ('Actor C', 22), ('', 17)]

In [19]:
df['cast'].dropna().str.split(', ').explode().value_counts()

cast
Actor A    37
Actor D    35
Actor B    24
Actor E    24
Actor F    24
Actor C    22
Name: count, dtype: int64