In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("data.xlsx")
df

,Actor,Film,Genre,Year,Box Office (Cr INR),IMDb Rating
0,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
1,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4
2,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0
3,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1
4,Ranveer Singh,Simmba,Action,2018,400,5.4
5,Hrithik Roshan,War,Action Thriller,2019,475,6.5
6,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
8,Vicky Kaushal,Uri,War,2019,342,8.2
9,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0

In [12]:
df.rename(columns={"IMDb Rating": "Rating"}, inplace=True)
df

,Actor,Film,Genre,Year,Box Office (Cr INR),Rating
0,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
1,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4
2,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0
3,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1
4,Ranveer Singh,Simmba,Action,2018,400,5.4
5,Hrithik Roshan,War,Action Thriller,2019,475,6.5
6,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
8,Vicky Kaushal,Uri,War,2019,342,8.2
9,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0

In [13]:
df.sort_values("Year")

,Actor,Film,Genre,Year,Box Office (Cr INR),Rating
1,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4
2,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0
4,Ranveer Singh,Simmba,Action,2018,400,5.4
5,Hrithik Roshan,War,Action Thriller,2019,475,6.5
6,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9
8,Vicky Kaushal,Uri,War,2019,342,8.2
9,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
0,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
3,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1

In [14]:
df.sort_values("Year",ascending=False)

,Actor,Film,Genre,Year,Box Office (Cr INR),Rating
0,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
3,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
8,Vicky Kaushal,Uri,War,2019,342,8.2
6,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9
5,Hrithik Roshan,War,Action Thriller,2019,475,6.5
9,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0
4,Ranveer Singh,Simmba,Action,2018,400,5.4
2,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0
1,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4

In [18]:
df2=df.sort_values(["Year","Rating"]).copy()

In [19]:
df2

,Actor,Film,Genre,Year,Box Office (Cr INR),Rating
1,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4
2,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0
4,Ranveer Singh,Simmba,Action,2018,400,5.4
5,Hrithik Roshan,War,Action Thriller,2019,475,6.5
6,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9
9,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0
8,Vicky Kaushal,Uri,War,2019,342,8.2
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
0,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
3,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1

In [25]:
df2.reset_index(drop=True,inplace=True)

In [21]:
df

,Actor,Film,Genre,Year,Box Office (Cr INR),Rating
0,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
1,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4
2,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0
3,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1
4,Ranveer Singh,Simmba,Action,2018,400,5.4
5,Hrithik Roshan,War,Action Thriller,2019,475,6.5
6,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
8,Vicky Kaushal,Uri,War,2019,342,8.2
9,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0

In [26]:
df2

,Actor,Film,Genre,Year,Box Office (Cr INR),Rating
0,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4
1,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0
2,Ranveer Singh,Simmba,Action,2018,400,5.4
3,Hrithik Roshan,War,Action Thriller,2019,475,6.5
4,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9
5,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0
6,Vicky Kaushal,Uri,War,2019,342,8.2
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
8,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
9,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1

In [27]:
df2

,Actor,Film,Genre,Year,Box Office (Cr INR),Rating
0,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4
1,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0
2,Ranveer Singh,Simmba,Action,2018,400,5.4
3,Hrithik Roshan,War,Action Thriller,2019,475,6.5
4,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9
5,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0
6,Vicky Kaushal,Uri,War,2019,342,8.2
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5
8,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9
9,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1

In [34]:
df2["Rank"]=df2["Rating"].rank(ascending=False,method="dense")
df2

,Actor,Film,Genre,Year,Box Office (Cr INR),Rating,Rank
0,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0,8.0
2,Ranveer Singh,Simmba,Action,2018,400,5.4,10.0
3,Hrithik Roshan,War,Action Thriller,2019,475,6.5,7.0
4,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9,6.0
5,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0,5.0
6,Vicky Kaushal,Uri,War,2019,342,8.2,2.0
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5,3.0
8,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9,9.0
9,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1,4.0

In [33]:
df2

,Actor,Film,Genre,Year,Box Office (Cr INR),Rating,Rank
0,Aamir Khan,Dangal,Sports Drama,2016,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,Action,2017,565,6.0,8.0
2,Ranveer Singh,Simmba,Action,2018,400,5.4,10.0
3,Hrithik Roshan,War,Action Thriller,2019,475,6.5,7.0
4,Akshay Kumar,Good Newwz,Comedy Drama,2019,318,6.9,6.0
5,Ayushmann Khurrana,Dream Girl,Comedy,2019,200,7.0,5.0
6,Vicky Kaushal,Uri,War,2019,342,8.2,2.0
7,Ajay Devgn,Tanhaji,Historical,2020,367,7.5,3.0
8,Shah Rukh Khan,Pathaan,Action,2023,1050,5.9,9.0
9,Ranbir Kapoor,Animal,Action Drama,2023,915,7.1,4.0